version: '3.8'

services:
  django_app:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./django_app:/home/app/django_app/
      - staticfiles_vol:/home/app/django_app/staticfiles
      - media_vol:/home/app/django_app/media
    depends_on:
      postgres_db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - staticfiles_vol:/home/app/friendly/staticfiles
      - media_vol:/home/app/friendly/media
    ports:
      - ${NGINX_HOST_PORT}:80
    depends_on:
      - django_app

  postgres_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  staticfiles_vol:
  media_vol:
