# Generated by Django 5.0.1 on 2024-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_post_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
